### ISSUE TITLE
Player not loading in IE10

### ISSUE THREAD

**Issue by madmarten** [clappr/clappr#637]
The player will not initialize properly when using IE10. Try this page in IE10 http://beta.adventistplay.se/media/html/clapprvod.html

Look at the first two players.

**Comment by dayvson** [comment]
Try to download the latest version of the clappr-level-selector-plugin 0.0.10. It should fix the problem.

**Comment by madmarten** [comment]
Load the page in IE10 and you will see that the first and second player is not loading properly compared to IE11. 

The bottom player on the same page was used to illustrate a problem with loading the level selector plugin. This was reported in another issue and has been resoled with the latest version as you describe.

But this issue with IE10 is still not resolved.

**Comment by comjakma** [comment]
1. Not loaded "4b76590b32dab62bc95c1b7951efae78.swf".

2. Use the "Clapper.FlasHLS" plug-in, an error occurs on follow line. 
--> throw new ReferenceError(errorMessage);
"SCRIPT5022: Exception thrown and not caught"

**Comment by philcrump** [comment]
I can confirm the flash player does not load on http://cdn.clappr.io/ in IE10 using 
```
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
```
works however in IE11, Chrome, Firefox.

**Comment by leandromoreira** [comment]
@philcrump did you notice any error on console?

**Comment by philcrump** [comment]
No errors in the console.

The player appears as a blank white box, although the flash applet has loaded as right-clicking on it brings up the Adobe Flash context menu, with the text: *Movie not loaded...* No content plays however.

Screenshot: http://i.imgur.com/KMQao01.png

**Comment by philcrump** [comment]
The bug I referred to is fixed as of 0.2.34. Fixes were developed in #788

**Comment by flavioribeiro** [comment]
Thanks @philcrump. @madmarten feel free to reopen this if you think that makes sense
